### ISSUE TITLE
Make use of checkstyle.xml

### ISSUE THREAD

**Issue by CoXier** [drakeet/Floo#3]
How do you make use of `checkstyle.xml` ?

**Comment by drakeet** [comment]
I use an Idea plugin to check codes and apply the checkstyles.xml

**Comment by CoXier** [comment]
I think `gradle plugin`  works better because it  can force other contributors to check code style across `CI`.

**Comment by drakeet** [comment]
Thanks, may change to gradle later.

**Comment by CoXier** [comment]
Do you follow the rule of `checkstyle.xml` ?

**Comment by drakeet** [comment]
Not complete, but basically will follow it. I used checkstyle as a reference, rather than enforcing, because some rules of checkstyle is not good, but also troublesome to exclude, so I did not use gredle to enforce the check, in addition, the enforcement will also bring collaboration trouble.

**Comment by drakeet** [comment]
I have fixed all checkstyle's issues and Floo is fully in line with its `checkstyle.xml` now. Thank you for your reminder.
